apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |-
    <source>
      @type tail
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/fluentd*"]
      pos_file /tmp/fluentd-containers.log.pos
      tag kubernetes.*
      <parse>
        @type json
        # These two lines handle the K8s log timestamp correctly
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <match kubernetes.**>
      @type elasticsearch
      host quickstart-es-http.es-operator.svc
      port 9200
      scheme https
      ssl_verify false
      user elastic
      # Pull the password from the secret created by ECK
      password "#{ENV['ES_PASSWORD']}"
      logstash_format true
      logstash_prefix fluentd
      <buffer>
        @type file
        path /tmp/fluentd-elasticserch.buffer
        flush_interval 5s
      </buffer>
    </match>